@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

@url_api = http://{{host}}/api/v1

// Check healt web server
GET {{url_api}}/health

###

// Check routes not valids
GET {{url_api}}/adawdusers


###
// USERS
// GET request all records from db
GET {{url_api}}/users

###

// POST request store a record in DB
POST {{url_api}}/register 
Content-Type: {{contentType}}

{
  "name" : "QA Name",
  "username" : "1QAUsername",
  "email" : "q1a@example.com",
  "password" : "pwd12345"
}

###
POST {{url_api}}/register 
Content-Type: {{contentType}}

{
  "name" : "UserCreate",
  "username" : "uswerdcreate"
}

###
// GET request a records from db with ID = 1
GET {{url_api}}/users/4

###
// PATCH request update a records from db with ID = 1
PATCH  {{url_api}}/users/1
Content-Type: {{contentType}}

{
  "pato":"123"
}

###
PATCH http://localhost:3000/api/v1/users/4 HTTP/1.1
Content-Type: {{contentType}}

{
  "email" : "test@example.com"
}

###

POST  http://localhost:3000/api/v1/login HTTP/1.1

Content-Type: {{contentType}}
{
  "username" : "user123",
  "password" : "test@example.com"
}

###