@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

@url_api = http://{{host}}/api/v1

// Check healt web server
GET {{url_api}}/health

###

// Check routes not valids
GET {{url_api}}/adawdusers


###
// USERS
// GET request all records from db
GET {{url_api}}/users

###

// POST request store a record in DB
POST {{url_api}}/register 
Content-Type: {{contentType}}

{
  "name" : "john",
  "username" : "jo22hndoe",
  "email" : "john2s21@example.com",
  "password" : "pwdjd123"
}

###
// GET request a records from db with ID = 1
GET {{url_api}}/users/1
